Mrc 3272
mrc-ide/odin.dust pull request #102
Opened 2022-06-14 12:58 UTC by hillalex

2022-06-15 10:44 UTC, hillalex commented on tests/testthat/test-odin-dust.R
> -test_that("disallow output()", {
this just looked like a dupe

2022-06-20 10:13 UTC, richfitz requested changes
Looks good - just added a suggestion for a slightly better test of that age structured model

2022-06-20 10:13 UTC, richfitz commented on tests/testthat/test-odin-dust.R
> +  expect_silent(mod$run(1))
```suggestion
  cmp <- odin::odin("examples/age.R", target = "c")$new(I0 = 1, use_dde = TRUE)
  y_mode <- mod$run(10)
  y_odin <- cmp$run(c(0, 10))[2, -1]
  expect_equal(drop(y_mode), unname(y_odin))
```

2022-06-20 10:13 UTC, richfitz commented on R/generate_dust.R
> +    else {
sorry, tiny thing here - I can also update it in the following PR

2022-06-20 10:17 UTC, hillalex commented on R/generate_dust.R
> +    else {
```suggestion
    } else {
```

2022-06-20 10:29 UTC, richfitz approved these changes

2022-06-20 10:56 UTC, merged