Proof of concept new compare function
mrc-ide/odin.dust pull request #131
Opened 2023-05-24 15:54 UTC by richfitz

A proof of concept automatic compiled compare function using the new odin support for describing compare and data.

~Note that this does not currently work with ode models it seems~

~Uses https://github.com/mrc-ide/odin/pull/294~

2023-06-16 17:11 UTC, weshinsley approved these changes
OK - this looks good to me and I nearly understand it - one question on generate_dust.R:680, and some things I need to look at myself more to understand what we're trying to do.

2023-06-16 17:11 UTC, weshinsley commented on tests/testthat/test-compare.R
> +    dnorm(d[[1]][[2]]$observed, drop(y), 0.5, TRUE))
Note for self - the gaps in my maths/stats make it not quite intuitive why/what/how these two are equal - but they are, and it works and that's how the comparison succeeds.

2023-06-21 09:52 UTC, r-ash requested changes
Looks good to me, just the comment about a missing `stop`

2023-06-21 09:52 UTC, r-ash commented on tests/testthat/test-gpu.R
> +  y <- mod$run(t[[1]])
Does this actually run on a GPU in this test?

2023-06-21 15:15 UTC, weshinsley requested changes
Just the package version to bump

2023-06-27 09:33 UTC, r-ash commented on tests/testthat/test-gpu.R
> +  y <- mod$run(t[[1]])
Ok nice, thought so! Didn't think there were any github action runners with a GPU about

2023-06-28 11:23 UTC, richfitz commented on R/generate_dust.R
> +}
I've added a test here to exercise this. But this just generates a sum over all the individual components

2023-06-28 11:23 UTC, richfitz commented on R/generate_dust_equation.R
> +    err <- setdiff(req, names(dat$gpu$access))
I've put the old assertion back in, as we don't expect this to fail with user input, just when we're refactoring

2023-06-28 11:31 UTC, r-ash approved these changes

2023-06-29 10:27 UTC, weshinsley approved these changes

2023-06-29 10:48 UTC, merged