Add GPU support
mrc-ide/odin.dust pull request #69
Opened 2021-03-03 09:31 UTC by richfitz

This PR activates new GPU support in odin.dust.

Changes here are fairly minor:

* split generating gpu-like code from compiling with NVCC
* annotate sum functions with HOSTDEVICE

I've also added the sirs example used to develop dustgpu, but we might swap that out for something a bit easier to push around at some point

Requires https://github.com/mrc-ide/dust/pull/187 to be merged, and then the DESCRIPTION here updated to remove the branch pin

2021-03-03 18:48 UTC, johnlees approved these changes
Are there any other odin functions other than these sums that might need a `HOSTDEVICE`?

2021-03-03 18:48 UTC, johnlees commented on DESCRIPTION
> +    mrc-ide/dust@i73-gpu,
```suggestion
    mrc-ide/dust,
```

2021-03-03 18:51 UTC, richfitz commented
> Are there any other odin functions other than these sums that might need a `HOSTDEVICE`?

Good question - I just checked and all the other functions are used just for the interface layer (so definitely just host based). If we add something like the fast round or accurate mod that'd need doing though

2021-03-03 22:09 UTC, johnlees requested changes

2021-03-03 22:09 UTC, johnlees commented on inst/library.hpp
> +  return x < y ? x : y;
```suggestion
  return x < y ? y : x;
```

2021-03-03 22:09 UTC, johnlees commented on tests/testthat/test-sexp.R
> +    "odin_min(a, odin_min(b, c))")
Haven't tested max?

2021-03-04 10:04 UTC, johnlees approved these changes

2021-03-04 10:12 UTC, merged